### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by hamen** [promeG/XLog#3]
Hi all
I'm trying to build and try out this project, because it seems to solve the Hugo + Retrolambda issue.
I edited my Gradle file, but I can't see any message in `logcat`. The whole Xposed framework thing is a bit unclear? Can't I use it as a normal Android Gradle library?

In the meantime, I'm trying to build your example, but I get:

``` bash
> Could not find property 'bintray_user' on com.jfrog.bintray.gradle.BintrayExtension_Decorated@11eed657.
```

Any ideas? Thanks

**Comment by promeG** [comment]
Hi hamen

You must install xposed framework and install XLog module, then enable XLog in Xposed Installer and reboot your phone.

[There is a clear guide for all these stuff.](http://www.addictivetips.com/android/what-is-xposed-framework-for-android-how-to-install-it-guide/)

[The link of XLog module.](http://repo.xposed.info/module/com.promegu.xlog.xposedmodule)

How to build XLog:

1 .  Add the following two lines to gradle.properties

``` groovy
bintray_user=xxx
bintray_api_key=xxx
```

2 .  Remove ':xlog-module' from settings.gradle

Please let me know if you have any futher questions.
