### ISSUE TITLE
Must the device that I debug on be rooted?

### ISSUE THREAD

**Issue by TonyTangAndroid** [promeG/XLog#6]
> Note that this only works with root access on Android 4.0.3 or later. Have a look at the support thread for instructions and FAQs.

This is from [Xposed Installer](http://repo.xposed.info/module/de.robv.android.xposed.installer). 

And since XLog requires Xposed Installer. Does mean that the device that I debug on be rooted?

**Comment by promeG** [comment]
Hi Tony,

I have just released version 2.0 which is no longer requires Xposed.

Fell free to use XLog on non-rooted devices!

**Comment by TonyTangAndroid** [comment]
Thanks a lot. I will try it out and let you know if there is anything that you should know.

**Comment by promeG** [comment]
Thanks.

BTW, here is the current support status(from dexposed).

_Dalvik runtime_
android 2.1/2.2 unsure
android2.3 **tested**
android3.0 unsure
android4.0-4.4 **tested**

_ART runtime_
android 4.4 unsure
android 5.0 **testing**
android 5.1 unsupported
